name: wmko-kpub
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.10
  - requests=2.31.0
  - matplotlib=3.8.2
  - jinja2
  - pyyaml
  - bokeh
  - openpyxl
  - pip
  - pip:
      - textract
