#!/bin/bash

# Using KPUB env?
python="python3"
if [ "$CONDA_PREFIX" != "" ]; then
    ENVS=($(conda env list | awk '{print $1}'))
    for env in "${ENVS[@]}"; do
        if [[ $env == *"KPUB"* ]]; then
            echo "Found KPUB conda environment"
            source $CONDA_PREFIX/etc/profile.d/conda.sh
            conda activate KPUB
            break
        fi
    done
fi

#script dir
root=`dirname $0`
mydir=`pwd`
cd $root

#regular singular kpub commands
a1=$1
if [ $a1 == 'update' ] \
    || [ $a1 == 'plot' ] \
    || [ $a1 == 'stats' ] \
    || [ $a1 == 'add' ] \
    || [ $a1 == 'delete' ] \
    || [ $a1 == 'import' ] \
    || [ $a1 == 'export' ] \
    || [ $a1 == 'spreadsheet' ]; then
    git pull
    $python src/kpub.py "$@"

#Do various exports and update github repo
elif [ $a1 == 'push' ]; then

    git pull 
    $python src/kpub.py export > data/kpub-export.csv
    $python src/kpub.py export --bibcodes > data/kpub-export-bibcodes.csv
    $python src/kpub.py export --bibcodes --archive > data/kpub-export-bibcodes-archive.csv
    git add data/kpub-export.csv
    git add data/kpub-export-bibcodes.csv
    git add data/kpub-export-bibcodes-archive.csv
    git add data/kpub.db
    git add data/plots/*
    git add data/output/*
    git commit -m "Regular db update"
    git push

# Update the metadata by re-fetching all entries from the ADS API
# this will e.g. update the citation counts and bibcodes
elif [ $a1 == 'refresh' ]; then
    git pull 
    $python src/kpub.py export > data/kpub-export.csv
    rm data/kpub.db
    $python src/kpub.py import data/kpub-export.csv

else
    echo "ERROR: Unknown kpub command: $a1"
    echo "    kpub update adds new publications by searching ADS (interactive)"
    echo "    kpub add adds a publication using its ADS bibcode"
    echo "    kpub delete deletes a publication using its ADS bibcode"
    echo "    kpub import imports bibcodes from a csv file"
    echo "    kpub export exports bibcodes to a csv file"
    echo "    kpub plot creates a visualization of the database"
    echo "    kpub stats saves publications stats in markdown format"
    echo "    kpub spreadsheet exports the publications to an Excel spreadsheet"
    echo "    kpub push to push the updated database to the git repo"
    echo "    kpub refresh to export and re-import all publications (this is slow and necessary only if you want to remove duplicates and fetch fresh citation statistics)"    
fi

cd $mydir