#!/bin/bash

#TODO: Add git pull to some of these?

# Using KPUB env?
python="python3"
if [ "$CONDA_PREFIX" != "" ]; then
    if [ -e $CONDA_PREFIX/envs/KPUB/bin/python3 ]; then
        python="$CONDA_PREFIX/envs/KPUB/bin/python3"
        source $CONDA_PREFIX/etc/profile.d/conda.sh
        conda activate KPUB
    fi
fi
echo $python


#script dir
root=`dirname $0`
mydir=`pwd`
cd $root

#regular singular kpub commands
a1=$1
if [ $a1 == 'update' ] \
    || [ $a1 == 'plot' ] \
    || [ $a1 == 'stats' ] \
    || [ $a1 == 'add' ] \
    || [ $a1 == 'delete' ] \
    || [ $a1 == 'import' ] \
    || [ $a1 == 'export' ] \
    || [ $a1 == 'spreadsheet' ]; then
    $python src/kpub.py "$@"

#Do various exports and update github repo
elif [ $a1 == 'push' ]; then

    $python src/kpub.py export > data/kpub-export.csv
    $python src/kpub.py export --bibcodes > data/kpub-export-bibcodes.csv
    $python src/kpub.py export --bibcodes --archive > data/kpub-export-bibcodes-archive.csv
    git add data/kpub-export.csv
    git add data/kpub-export-bibcodes.csv
    git add data/kpub-export-bibcodes-archive.csv
    git commit -m "Regular db update"
    git push

# Update the metadata by re-fetching all entries from the ADS API
# this will e.g. update the citation counts and bibcodes
elif [ $a1 == 'refresh' ]; then
    $python src/kpub.py export > data/kpub-export.csv
    rm data/kpub.db
    $python src/kpub.py import data/kpub-export.csv

else
    echo "ERROR: Unknown kpub command"
    
fi

cd $mydir